services:
  - type: web
    name: bot-panel
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ADMIN_USER
        value: admin
      - key: ADMIN_PASS
        value: admin123
      - key: BOT_SECRET
        value: ce97679edf2b661ed08f6775508cf0fd